name: intervalprogressbar
description: A interval progress bar for Flutter. Horizontal, vertical, colorful and interval progress.
version: 3.0.0
homepage: https://github.com/e-welina/IntervalProgressBar.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
